In [23]:
from pathlib import Path
import pandas as pd

In [24]:
PARSED_DIR = Path("../data/parsed")

def read_all_parsed_csv(parsed_dir: Path = PARSED_DIR) -> pd.DataFrame:
    files = sorted(parsed_dir.glob("**/*.csv"))

    if not files:
        raise FileNotFoundError(f"No CSV files found in {parsed_dir}")

    dfs = []

    for file in files:
        df = pd.read_csv(file)

        relative_path = file.relative_to(parsed_dir)
        df["parsed_file"] = str(relative_path)

        if len(relative_path.parts) >= 2:
            df["tournament_id_from_path"] = relative_path.parts[0]
            df["category_from_path"] = file.stem

        dfs.append(df)

    return pd.concat(dfs, ignore_index=True)

In [25]:
def read_single_parsed_csv(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    return df

In [26]:
df = read_all_parsed_csv()

In [27]:
df['kata_name']

0      Gojushiho Sho
1            Papuren
2      Gojushiho Dai
3           Anan Dai
4           Anan Dai
           ...
211       Suparinpei
212             Unsu
213         Ohan Dai
214             Unsu
215    Gojushiho Sho
Name: kata_name, Length: 216, dtype: str

In [28]:
kata_usage = (
    df.groupby("kata_name")
    .size()
    .reset_index(name="performances")
    .sort_values("performances", ascending=False)
)
kata_usage

              kata_name  performances
20           Suparinpei            33
16              Papuren            28
8         Gojushiho Sho            20
2   Chatanyara Kushanku            19
7         Gojushiho Dai            18
22                 Unsu            17
1              Anan Dai            13
3   Chibana No Kushanku            13
5               Gankaku            12
10            Kururunfa            10
14             Ohan Dai             7
12              Nipaipo             5
18            Shisochin             4
0                  Anan             3
19               Sochin             3
9             Kanku Sho             3
17               Seisan             2
6             Gojushiho             1
4                  Enpi             1
13                 Ohan             1
11            Nijushiho             1
15  Oyadomari No Passai             1
21        Tomari Bassai             1

In [29]:
kata_usage = (
    df.groupby("kata_name")
    .size()
    .reset_index(name="performances")
    .sort_values("performances", ascending=False)
)

kata_usage["percentage"] = (
    kata_usage["performances"] / kata_usage["performances"].sum() * 100
)

kata_usage.head(20)

              kata_name  performances  percentage
20           Suparinpei            33   15.277778
16              Papuren            28   12.962963
8         Gojushiho Sho            20    9.259259
2   Chatanyara Kushanku            19    8.796296
7         Gojushiho Dai            18    8.333333
22                 Unsu            17    7.870370
1              Anan Dai            13    6.018519
3   Chibana No Kushanku            13    6.018519
5               Gankaku            12    5.555556
10            Kururunfa            10    4.629630
14             Ohan Dai             7    3.240741
12              Nipaipo             5    2.314815
18            Shisochin             4    1.851852
0                  Anan             3    1.388889
19               Sochin             3    1.388889
9             Kanku Sho             3    1.388889
17               Seisan             2    0.925926
6             Gojushiho             1    0.462963
4                  Enpi             1    0.462963
13                 Ohan             1    0.462963

In [30]:
df[df["player_name"] == "TORRES GUTIERREZ ARIEL"]

,player_name,player_id,kata_nr,kata_name,winner,tournament_id,category,source_file,parsed_file,tournament_id_from_path,category_from_path
141,TORRES GUTIERREZ ARIEL,3006,64,Ohan Dai,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
145,TORRES GUTIERREZ ARIEL,3006,90,Shisochin,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
149,TORRES GUTIERREZ ARIEL,3006,47,Kururunfa,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
201,TORRES GUTIERREZ ARIEL,3006,2,Anan Dai,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
207,TORRES GUTIERREZ ARIEL,3006,92,Suparinpei,False,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
213,TORRES GUTIERREZ ARIEL,3006,64,Ohan Dai,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male

In [31]:
df[df["player_name"] == "NISHIYAMA KAKERU"]

,player_name,player_id,kata_nr,kata_name,winner,tournament_id,category,source_file,parsed_file,tournament_id_from_path,category_from_path
189,NISHIYAMA KAKERU,26561,47,Kururunfa,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
193,NISHIYAMA KAKERU,26561,90,Shisochin,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
197,NISHIYAMA KAKERU,26561,86,Seisan,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
205,NISHIYAMA KAKERU,26561,68,Papuren,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
209,NISHIYAMA KAKERU,26561,92,Suparinpei,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
211,NISHIYAMA KAKERU,26561,92,Suparinpei,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male

In [32]:
df[df["player_name"].str.contains('MOTO')]

,player_name,player_id,kata_nr,kata_name,winner,tournament_id,category,source_file,parsed_file,tournament_id_from_path,category_from_path
128,KEN OKAMOTO,97868,12,Enpi,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
131,KEN OKAMOTO,97868,21,Gojushiho Sho,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
135,KEN OKAMOTO,97868,20,Gojushiho Dai,False,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
140,MOTO RYUJI,37096,91,Sochin,False,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
143,MOTO RYUJI,37096,21,Gojushiho Sho,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
147,MOTO RYUJI,37096,60,Nijushiho,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
165,MOTO KAZUMASA,37253,91,Sochin,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
169,MOTO KAZUMASA,37253,99,Unsu,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
173,MOTO KAZUMASA,37253,20,Gojushiho Dai,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
203,MOTO KAZUMASA,37253,21,Gojushiho Sho,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
208,MOTO KAZUMASA,37253,15,Gankaku,False,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male
215,MOTO KAZUMASA,37253,21,Gojushiho Sho,True,2026_06_k1_premier_rabat,kata_male,2026_06_k1_premier_rabat\kata_male.html,2026_06_k1_premier_rabat\kata_male.csv,2026_06_k1_premier_rabat,kata_male

In [33]:
def summarize_kata_usage(df: pd.DataFrame) -> pd.DataFrame:
    summary = (
        df.groupby(["category", "kata_name"])
        .agg(
            performances=("kata_name", "size"),
            wins=("winner", "sum"),
            unique_athletes=("player_id", "nunique"),
        )
        .reset_index()
    )

    summary["total_category_performances"] = (
        summary.groupby("category")["performances"].transform("sum")
    )

    summary["usage_pct"] = (
        summary["performances"] / summary["total_category_performances"] * 100
    )

    summary["win_rate"] = summary["wins"] / summary["performances"] * 100

    summary = summary.sort_values(
        ["category", "performances", "win_rate"],
        ascending=[True, False, False],
    )

    return summary

In [37]:
test_path='../data/parsed/2026_06_k1_premier_rabat/kata_male.csv'
df = read_single_parsed_csv(Path(test_path))
summarize_kata_usage(df)

,category,kata_name,performances,wins,unique_athletes,total_category_performances,usage_pct,win_rate
18,kata_male,Suparinpei,15,8,13,114,13.157895,53.333333
7,kata_male,Gojushiho Sho,14,7,13,114,12.280702,50.000000
19,kata_male,Unsu,13,6,11,114,11.403509,46.153846
6,kata_male,Gojushiho Dai,10,3,10,114,8.771930,30.000000
14,kata_male,Papuren,8,5,8,114,7.017544,62.500000
5,kata_male,Gankaku,8,1,8,114,7.017544,12.500000
9,kata_male,Kururunfa,6,6,6,114,5.263158,100.000000
1,kata_male,Anan Dai,6,3,6,114,5.263158,50.000000
2,kata_male,Chatanyara Kushanku,6,1,6,114,5.263158,16.666667
13,kata_male,Ohan Dai,5,2,4,114,4.385965,40.000000
16,kata_male,Shisochin,4,3,4,114,3.508772,75.000000
3,kata_male,Chibana No Kushanku,4,1,4,114,3.508772,25.000000
11,kata_male,Nipaipo,3,3,3,114,2.631579,100.000000
17,kata_male,Sochin,3,2,3,114,2.631579,66.666667
15,kata_male,Seisan,2,2,2,114,1.754386,100.000000
0,kata_male,Anan,2,1,2,114,1.754386,50.000000
8,kata_male,Kanku Sho,2,0,2,114,1.754386,0.000000
4,kata_male,Enpi,1,1,1,114,0.877193,100.000000
10,kata_male,Nijushiho,1,1,1,114,0.877193,100.000000
12,kata_male,Ohan,1,1,1,114,0.877193,100.000000